In [13]:
#  프로그램의 외부에 저장된 파일을 읽는 여러 가지 방법 p.173
# readlines 'a'

f = open("C:/Users/CPB06GameN/myjupiterfiles/쓰기파일2.txt", "a")
for i in range(11, 20):
    data = "%d 번째 줄입니다.\n" % i
    f.write("aaa")
f.close()


In [15]:
# 자동으로 닫아주는 with문
with open("C:/Users/CPB06GameN/myjupiterfiles/쓰기파일2.txt", "w") as f:
    f.write("Life is too short, you need python")

In [24]:
########## p.188 사칙연산 클래스 만들기
class FourCal:
    #self.first
    #self.second
    def __init__(self):
        self.first = a
        self.second = b
    def add(self):
        result = self.first + self.second
        return result
    def mul(self):
        result = self.first * self.second
        return result
class MoreFourCal(FourCal):
    def pow(self):
        result = self.first*self.second
        return result
    def div(self):
        if self.second == 0:
            self.second = 0.00000000000000000001
            result
c = MoreFourCal(4,2)
d = c.pow()
print(d)


TypeError: __init__() takes 1 positional argument but 3 were given

In [26]:
class MyMAth:
    MyPI = 3.14
mm1 = MyMath()
mm1.MyPI = 4
mm2 = MyMath()
print(mm1.MyPI, mm2MyPI)



NameError: name 'MyMath' is not defined

In [48]:
import mod1
print(mod1.add_mod1(3, 4))
print(mod1.sub_mod1(3, 4))


7


AttributeError: module 'mod1' has no attribute 'sub_mod1'

In [49]:
import mod2
print(mod2.add_mod2(3, 4))
print(mod2.PI)


7
3.14


In [50]:
import mod2
print(mod2.add_mod2(3, 4))
print(mod2.PI)
mm2 = mod2.Math_mod2()
print(mm2.solve(2))

7
3.14
12.56


In [54]:
##### 패키지
import numpy as np
import pandas as pd
import matplotlib, pyplot as plt

ModuleNotFoundError: No module named 'pandas'

In [61]:
try:
    print(4/0)
except ZeroDivisionError as e:
    print(4/0.0000000000000000001)
    print(e)


4e+19
division by zero


In [75]:
######## p.231 내장함수
def positive(l):
    result = []
    for i in l:
        if i > 0:
            result.append(i)
    return result
print(positive[1, -3, 2, 0, -5, 6])

TypeError: 'function' object is not subscriptable

In [76]:
def positive(x):
    return x > 0
data = [1, -3, 2, 0, -5, 6]
f = filter(positive, data)
print(list(f))

[1, 2, 6]


In [78]:
# lambda p.166
data = [1,-3,2,0,-5,6]
#f = filter(positive, data)
list(filter(lambda x: x>0, data))



[1, 2, 6]

In [81]:
a, b = input("숫자 두개를 입력하세요").split()
a = int(a)
b = int(b)
print(a+1,"그리고",b+1)

숫자 두개를 입력하세요10 20
11 그리고 21


In [82]:
a, b = map(int, input("숫자 두개를 입력하세요").split())
print(a+1,"그리고",b+1)

숫자 두개를 입력하세요d


ValueError: invalid literal for int() with base 10: 'd'

In [84]:
a, b, c, d, e = map(int, input("숫자 5개를 입력하세요").split())
print(a+1,b+1,c+1,d+1,e+1)

숫자 5개를 입력하세요


ValueError: not enough values to unpack (expected 5, got 0)

In [91]:
# 두개의 데이터 셋을 하나의 튜플로 묶는 경우.
data1 = [1, 2, 3]
data2 = [4, 5, 6]
list(zip(data1, data2))

[(1, 4), (2, 5), (3, 6)]

In [93]:
# 세개
data3 = [1, 2, 3]
data4 = [4, 5, 6]
data5 = [4, 5, 6]
list(zip(data3, data4, data5))

[(1, 4, 4), (2, 5, 5), (3, 6, 6)]

In [95]:
############## OS  p.250
# import os 필요
# 환경정보 보기
import os
os.environ

environ{'ALLUSERSPROFILE': 'C:\\ProgramData',
        'APPDATA': 'C:\\Users\\CPB06GameN\\AppData\\Roaming',
        'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files',
        'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files',
        'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files',
        'COMPUTERNAME': 'USER032984782',
        'COMSPEC': 'C:\\WINDOWS\\system32\\cmd.exe',
        'DRIVERDATA': 'C:\\Windows\\System32\\Drivers\\DriverData',
        'HOMEDRIVE': 'C:',
        'HOMEPATH': '\\Users\\CPB06GameN',
        'JAVA_HOME': 'C:\\Program Files\\Java\\jdk1.8.0_291',
        'LOCALAPPDATA': 'C:\\Users\\CPB06GameN\\AppData\\Local',
        'LOGONSERVER': '\\\\USER032984782',
        'NUMBER_OF_PROCESSORS': '12',
        'ONEDRIVE': 'C:\\Users\\CPB06GameN\\OneDrive',
        'OS': 'Windows_NT',
        'PATH': 'C:\\Users\\CPB06GameN\\.conda\\envs\\melchiorist;C:\\Users\\CPB06GameN\\.conda\\envs\\melchiorist\\Library\\mingw-w64\\bin;C:\\Users\\CPB06GameN\

In [99]:
############## OS  p.250
# import glob 필요
# 
import glob # 특정 디렉터리에 있는 파일 이름 모두를 알아야 할 때 쓰는 모듈. ( 디렉터리에 있는 파일들을 리스트로 만들어줌)
glob.glob ('C:\\Users\CPB06GameN\\myjupiterfiles\\*.*')

['C:\\Users\\CPB06GameN\\myjupiterfiles\\210517.ipynb',
 'C:\\Users\\CPB06GameN\\myjupiterfiles\\210521.ipynb',
 'C:\\Users\\CPB06GameN\\myjupiterfiles\\210525 - 4장 함수.ipynb',
 'C:\\Users\\CPB06GameN\\myjupiterfiles\\210525 - 연습문제 2.ipynb',
 'C:\\Users\\CPB06GameN\\myjupiterfiles\\210526 - 4장 함수.ipynb',
 'C:\\Users\\CPB06GameN\\myjupiterfiles\\mod1.py',
 'C:\\Users\\CPB06GameN\\myjupiterfiles\\mod2.py',
 'C:\\Users\\CPB06GameN\\myjupiterfiles\\myjupiterfiles.zip',
 'C:\\Users\\CPB06GameN\\myjupiterfiles\\Untitled-Copy1.ipynb',
 'C:\\Users\\CPB06GameN\\myjupiterfiles\\Untitled.ipynb',
 'C:\\Users\\CPB06GameN\\myjupiterfiles\\Untitled1.ipynb',
 'C:\\Users\\CPB06GameN\\myjupiterfiles\\Untitled2.ipynb',
 'C:\\Users\\CPB06GameN\\myjupiterfiles\\쓰기파일.txt',
 'C:\\Users\\CPB06GameN\\myjupiterfiles\\쓰기파일1.txt',
 'C:\\Users\\CPB06GameN\\myjupiterfiles\\쓰기파일2.txt']

In [109]:
####### 시간
# 
import time

#time.time() # utc를 사용 1970 1월 1일 부터 0시 0분 0초 기준 초단위로 돌려준 결과
time.localtime(time.time())
time.asctime(time.localtime(time.time())) #time.localtime에 의해서 반환된 튜플 형태의 값을 인수로 받아서 날짜와 시간을 알아보기 쉬운형태로 돌려주는 함수.


'Wed May 26 16:10:48 2021'

In [110]:
for i in range(10):
    print(i)
    time.sleep(1)
    

0
1
2
3
4
5
6
7
8
9


In [114]:
##### 넘파이 와 연산 코드 차이 비교
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(100000))
%time for i in range(10): my_arr2=my_arr*2

Wall time: 14.4 ms


In [116]:
##### 넘파이 와 연산 코드 차이 비교
%time for i in range(10): my_list2=[x *2 for x in my_list]

Wall time: 56.4 ms


In [117]:
data = np(data, np randrm)

SyntaxError: invalid syntax (<ipython-input-117-460ad1692099>, line 1)

In [118]:
data * 10

[1,
 -3,
 2,
 0,
 -5,
 6,
 1,
 -3,
 2,
 0,
 -5,
 6,
 1,
 -3,
 2,
 0,
 -5,
 6,
 1,
 -3,
 2,
 0,
 -5,
 6,
 1,
 -3,
 2,
 0,
 -5,
 6,
 1,
 -3,
 2,
 0,
 -5,
 6,
 1,
 -3,
 2,
 0,
 -5,
 6,
 1,
 -3,
 2,
 0,
 -5,
 6,
 1,
 -3,
 2,
 0,
 -5,
 6,
 1,
 -3,
 2,
 0,
 -5,
 6]

In [119]:
data + data

[1, -3, 2, 0, -5, 6, 1, -3, 2, 0, -5, 6]

In [120]:
data.shape

AttributeError: 'list' object has no attribute 'shape'

In [121]:
data2d = [[1, 2, 3, 4], [5, 6, 7, 8]]
data2d

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [123]:
arr2d = no.array(data2d)

NameError: name 'no' is not defined

In [124]:
arr2d.ndim

NameError: name 'arr2d' is not defined

In [126]:
arr2d.shape

NameError: name 'arr2d' is not defined

In [131]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [133]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [136]:
np.zeros((2, 3, 2)).dtype

dtype('float64')

In [138]:
arr = np.zeros((2, 3, 2), dtype=np.int32)
arr.dtype

dtype('int32')

In [140]:
arr1 = np.zeros((2, 3))
arr2 = np.ones_like((arr1))
arr2.shape
arr2


array([[1., 1., 1.],
       [1., 1., 1.]])