In [5]:
### p.142 numpy 자료형
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
arr.dtype    # 데이터 타입으로 바꿈

dtype('int32')

In [6]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [7]:
float_arr

array([1., 2., 3., 4., 5.])

In [8]:
received = input("데이터 5개 입력하세요").split()
str_num_arr = np.array(received, dtype=np.string_)
str_num_arr.dtype

데이터 5개 입력하세요1 2 3 4 5


dtype('S1')

In [10]:
numer_num_arr = str_num_arr.astype(float)
numer_num_arr.dtype

dtype('float64')

In [13]:
# NumPy 배열의 산술 연산 p.142~143
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [15]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [16]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [19]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [22]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [24]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [44]:
# 색인과 슬라이싱 기초
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
arr[5]

5

In [46]:
arr[5:8]

array([5, 6, 7])

In [47]:
arr[5:8] = 12

In [48]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [50]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [51]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [52]:
arr_slice[ : ] = 64 # 단순히 [:]로 슬라이스를 하면 배열의 모든 값을 할당한다.
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [54]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9,]])
arr2d[2]


array([7, 8, 9])

In [56]:
arr2d[0][2]


3

In [58]:
arr2d[0, 2]

3

In [63]:
arr2d[2:, :]

array([[7, 8, 9]])

In [65]:
arr2d[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [69]:
namedata = ["Bob","Joe","Will","Bob","Will","Joe","Joe"]
names = np.array(namedata)
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [89]:
rand_data = np.random.randn(7,4)
rand_data

array([[ 0.93751253,  2.11265798,  0.78307089,  0.35139335],
       [-0.44541605, -0.64032323,  1.35942487,  0.31827304],
       [ 1.33197459,  0.94416827, -0.51658596, -0.5459245 ],
       [ 0.0469237 ,  0.13496616,  0.03009256, -0.86402297],
       [ 1.74692851, -0.9896152 , -1.94113534, -0.61788191],
       [-0.19425194,  1.29928916,  1.08969296, -0.86388438],
       [-0.53731767, -1.84126626, -2.18419786, -0.58452385]])

In [91]:
names == "Bob"
#array(["Bob","Joe","Will","Bob","Will","Joe","Joe"])

array([ True, False, False,  True, False, False, False])

In [94]:
rand_data[names == "Bob"]

array([[ 0.93751253,  2.11265798,  0.78307089,  0.35139335],
       [ 0.0469237 ,  0.13496616,  0.03009256, -0.86402297]])

In [97]:
# 4.1.7 배열 전치와 축 바꾸기
arr = np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [98]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [101]:
arr = np.random.randn(6, 3)
arr

array([[ 0.32048411, -0.38738714,  0.96493399],
       [ 0.22106103, -0.41843424, -0.92566417],
       [ 1.23735534,  0.82797229, -1.26468056],
       [-0.40939618,  0.35782408,  0.68979392],
       [ 0.24680124, -0.12077731,  0.26142335],
       [ 0.08134898,  1.69289605,  0.24626372]])

In [103]:
np.dot(arr.T, arr) #3 x 6 6 x 3 = 3 x 3

array([[ 1.91776002,  0.76926058, -1.6580876 ],
       [ 0.76926058,  4.01921638, -0.40144415],
       [-1.6580876 , -0.40144415,  3.99217232]])

In [105]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [108]:
arr.transpose((1, 0, 2))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [119]:
arr.swapaxes(1, 2) # 데이터를 복사하지 않고 원래 데이터에 대한 뷰를 반환
arr

AxisError: axis1: axis 1 is out of bounds for array of dimension 1

In [129]:
#p.153
arr = np.arange(10)
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [116]:
arr = np.arange(10)
np.exp(arr) # expernantial 지수근 구하기

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [131]:
# p.158
# 4.2 유니버설 함수 : 배열의 각 원소를 빠르게 처리하는 함수 
# ufunc 함수. ndarray안에 있는 데이터 원소별로 연산을 수행하는 함수.
x = np.random.randn(4)
y = np.random.randn(4)
z = np.maximum(x, y) # 이항 유니버셜 함수
print(x);print(y);print(z)

[ 0.62116771 -0.40171337 -0.3084949   0.700357  ]
[-0.35827898  1.7216912   1.51824493  0.16176799]
[0.62116771 1.7216912  1.51824493 0.700357  ]


In [132]:
# p.161
# 4.3 배열을 이용한 배열지향 프로그래밍
points = np.arange(-5, 5, 0.01) # -5부터 4.99까지 0.01씩 증가하는 값들의 배열
xs, ys = np.meshgrid(points, points)
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ...,
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])